/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.2.2/userguide/java_library_plugin.html
 */

plugins {
    `java-library`
    `maven-publish`
    jacoco
}

repositories {
    mavenLocal()
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

dependencies {
    implementation(project(":event-stream-rpc-model"))
    implementation("com.google.code.gson:gson:2.8.6")
    implementation("software.amazon.awssdk.crt:aws-crt:1.0.0-SNAPSHOT")

    testCompileOnly("org.junit.jupiter:junit-jupiter-api:5.4.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.4.0")
    testCompileOnly("org.junit.jupiter:junit-jupiter-params:5.4.0")

    //pull in server for tests
    testImplementation(project(":test-model-codegen"))
    testImplementation(project(":event-stream-rpc-client"))
    testImplementation("org.junit.platform:junit-platform-console-standalone:1.7.0")
}

val test by tasks.getting(Test::class) {
    // Use junit platform for unit tests
    useJUnitPlatform()
}

/*
 * CheckStyle
 * ====================================================
 */
//disabled due to how generated code is included in normal source
//apply(plugin = "checkstyle")
//tasks["checkstyleTest"].enabled = false

/*
 * Tests
 * ====================================================
 *
 * Configure the running of tests.
 */
// Log on passed, skipped, and failed test events if the `-Plog-tests` property is set.
if (project.hasProperty("log-tests")) {
    tasks.test {
        testLogging.events("passed", "skipped", "failed")
    }
}

/*
 * Code coverage
 * ====================================================
 */
apply(plugin = "jacoco")

// Always run the jacoco test report after testing.
tasks["test"].finalizedBy(tasks["jacocoTestReport"])

// Configure jacoco to generate an HTML report.
tasks.jacocoTestReport {
    reports {
        xml.isEnabled = false
        csv.isEnabled = false
        html.destination = file("$buildDir/reports/jacoco")
    }
}