/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.2.2/userguide/java_library_plugin.html
 */

description = "Generates Java code from Smithy models"
extra["displayName"] = "Smithy :: Java :: Codegen"
extra["moduleName"] = "software.amazon.smithy.java.codegen"

dependencies {
    compile("com.squareup:javapoet:1.13.0")
    api("software.amazon.smithy:smithy-codegen-core:[1.0.2,1.1.0[")
    api("com.atlassian.commonmark:commonmark:0.14.0")
    api("org.jsoup:jsoup:1.13.1")
    implementation("software.amazon.smithy:smithy-protocol-test-traits:[1.0.2,1.1.0[")
}
