/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.2.2/userguide/java_library_plugin.html
 */

plugins {
    id("software.amazon.smithy").version("0.5.0")
    `java-library`
}

repositories {
    mavenLocal()
    mavenCentral()
}

tasks.compileJava {
    dependsOn("smithyBuildJar")
}

sourceSets {
    main {
        java {
            srcDirs("${buildDir}/smithyprojections/test-model-codegen/source/event-stream-rpc-java/client/",
                    "${buildDir}/smithyprojections/test-model-codegen/source/event-stream-rpc-java/model/",
                    "${buildDir}/smithyprojections/test-model-codegen/source/event-stream-rpc-java/server/")
        }
    }
}

dependencies {
    implementation(project(":smithy-event-stream-rpc-java"))
    implementation(project(":smithy-event-stream-rpc-python"))
    implementation(project(":event-stream-rpc-model"))
    implementation(project(":event-stream-rpc-client"))
    implementation(project(":event-stream-rpc-server"))

    compileOnly("org.junit.jupiter:junit-jupiter-api:5.4.0")
    compileOnly("org.junit.jupiter:junit-jupiter-params:5.4.0")
    runtimeOnly("org.junit.jupiter:junit-jupiter-engine:5.4.0")

    implementation("software.amazon.awssdk.crt:aws-crt:1.0.0-SNAPSHOT")
    implementation("com.google.code.gson:gson:2.8.6")
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
