/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.2.2/userguide/multi_project_builds.html
 */

rootProject.name = "smithy-java"

include(":smithy-event-stream-rpc-java")
include(":smithy-event-stream-rpc-python")

//definitely include the following three in open source
include(":event-stream-rpc-server")
include(":event-stream-rpc-client")
include(":event-stream-rpc-model")
include(":test-model-codegen") //generates and builds from a "PetShop" model to test this set of libraries

//convenience projects for greengrass project iteration
include(":greengrass-client")
include(":greengrass-server")

pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
    }
}
