name: Release

on:
  release:
    types: [created]

jobs:
  update-version:
    runs-on: ubuntu-20.04 # latest
    permissions:
      contents: write # allow push

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update Version
      run: ./update-version.sh ${{ secrets.GITHUB_TOKEN }} ${{ secrets.TAG_PR_TOKEN }}

    - name: configure AWS credentials (Release)
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_CI_RELEASE }}
        aws-region: us-east-1

    - name: Trigger Release
      aws s3 cp VERSION ${{ secrets.AWS_CI_RELEASE_S3_URL }}
